<a href="https://colab.research.google.com/github/sevval-345/-product-return-risk-score/blob/main/Quiz2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1.Soru

Yeni 1 Python listesi oluşturup bunu Numpy Array'e dönüştürün. Ardından tip özelliğini kontrol edin

In [1]:
import numpy as np
liste=[10,20,30,40,50]
array=np.array(liste)
print(type(array))


<class 'numpy.ndarray'>


### 2.Soru


Numpy Array oluşturup tip değerini "int" olarak ayarlayınız

In [2]:
arr=np.array([1,2,3,4,5],dtype="int")
print(arr.dtype)

int64


### 3.Soru

Tüm değerleri 5 olan 4x4 boyutunda 1 matri oluşturun

In [3]:
arr=np.full((4,4),5)
print(arr)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


### 4.Soru

"0-56" arası artış değeri "5" olacak şekilde bir Numpy Array oluşturun. Oluşturulan bu tek boyutlu Numpy
Array'i 3x4 boyutunda bir matrise dönüştürün.



In [4]:
tek_boyutlu_array=np.arange(0,56,5)
matris=tek_boyutlu_array.reshape(3,4)
print(matris)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


### 5.Soru
"0-100" arasında rastgele değerlerden oluşan ve toplam 12 eleman içeren bir Numpy Array oluşturun.
Ardından bu Numpy Array'i uygun boyutlarda bir matrise dönüştürün.

In [6]:
rastgele_array=np.random.randint(0,100,12)
matris=rastgele_array.reshape(3,4)
print(matris)

[[32 32 10 41]
 [12 52 12 21]
 [60 17 33  7]]


### 6.Soru
3x3 boyutunda bir Numpy Array oluşturun. (Yontem size bağlı. arange, random vb .. ) Ardından bu Numpy
Array'i tek boyutlu bir Array'e (vektör) dönüştürün.

In [7]:
matris=np.array([[1,2,3],[4,5,6],[7,8,9]])
tek_boyutlu_array=matris.flatten()
print(tek_boyutlu_array)

[1 2 3 4 5 6 7 8 9]


In [8]:
matris=np.arange(1,10).reshape(3,3)
tek_boyutlu_array=matris.reshape(-1)
print(tek_boyutlu_array)

[1 2 3 4 5 6 7 8 9]


### 7.Soru
4x4 boyutunda 1 Numpy oluşturup sırasıyla şu özellikleri kontrol edin.

· Array'in boyutu
· Array'in veri tipi
· Array'in topiam eleman sayısı
· Array'in boyut sayısı

In [9]:
arr=np.random.randint(0,100,16).reshape(4,4)
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)

(4, 4)
int64
16
2
